const CREATE_RULES = {
  SUPER_ADMIN: ['PROVINCE_ADMIN', 'DISTRICT_ADMIN', 'STATION_ADMIN', 'POLICE'],
  PROVINCE_ADMIN: ['DISTRICT_ADMIN', 'STATION_ADMIN', 'POLICE'],
  DISTRICT_ADMIN: ['STATION_ADMIN', 'POLICE'],
  STATION_ADMIN: ['POLICE'],
  POLICE: [],
};

const ALL_USER_ROLES = [
  'SUPER_ADMIN',
  'PROVINCE_ADMIN',
  'DISTRICT_ADMIN',
  'STATION_ADMIN',
  'POLICE',
];

const CREATABLE_ROLES = ALL_USER_ROLES.filter((role) => role !== 'SUPER_ADMIN');

module.exports = {
  ALL_USER_ROLES,
  CREATABLE_ROLES,
  CREATE_RULES,
};
